language: ja-JP
reviews:
  path_filters:
    - node_modules/
    - .DS_Store
    - .next/
    - .env
    - .env.example
    - .gitignore
    - build/
    - dist/
    - out/
    - generated/
    - .tmp/
    - .turbo/
  auto_review:
    enabled: false
code_generation:
  docstrings:
    language: ja-JP
